apiVersion: spring-boot-camel.eformat.me/v1alpha1
kind: SpringBootCamel
metadata:
  name: spring-boot-camel
spec:
  # Add fields here
  size: 1
  greeting_message: "Hello Ansible Operators R0ck !"
  greeting_timeout: 3000
